#!/usr/bin/env python
# coding: utf-8

# # SPT Data Process

# ## Query Data from Openground Database 

# Use the spt_process module in the 'hapy' package.

# In[1]:


from hapy.spt_process import spt_process as sp


# User needs to copy and paste the token generated by the Postman. Remeber that the format of the token is *`Bearer`+`token`*. In other words, only replace the non-sense string after the `Bearer`.

# In[2]:



# token (from Postman)
# the format is: Bearer token
token = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJlbnRsZXlJTVMiLCJwaS5hdG0iOiJhOG1lIn0.eyJzY29wZSI6WyJvcGVuZ3JvdW5kIiwiZW1haWwiLCJvcGVuaWQiLCJwcm9maWxlIl0sImNsaWVudF9pZCI6Im9wZW5ncm91bmQtY2xvdWQtY29ubmVjdG9yIiwiYXVkIjpbImh0dHBzOi8vaW1zLmJlbnRsZXkuY29tL2FzL3Rva2VuLm9hdXRoMiIsImh0dHBzOi8vaW1zb2lkYy5iZW50bGV5LmNvbS9hcy90b2tlbi5vYXV0aDIiLCJodHRwczovL2ltc29pZGMuYmVudGxleS5jb20vcmVzb3VyY2VzIiwib3Blbmdyb3VuZC1jbG91ZCJdLCJzdWIiOiIxZTU3ZjNlMS1jZGE3LTQ5NTUtYTc2Yi00MDhkMTZlNzNhYjYiLCJvcmciOiI5MDE3OGUzYy0wZTk0LTQ0ZTUtYWE4OS1iZDgxNTNmOTVmNDIiLCJzdWJqZWN0IjoiMWU1N2YzZTEtY2RhNy00OTU1LWE3NmItNDA4ZDE2ZTczYWI2IiwiaXNzIjoiaHR0cHM6Ly9pbXNvaWRjLmJlbnRsZXkuY29tIiwiZW50aXRsZW1lbnQiOlsiU0VMRUNUXzIwMDYiLCJTRUxFQ1QiLCJCRE4iXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiaGhlQGhhbGV5YWxkcmljaC5jb20iLCJnaXZlbl9uYW1lIjoiSGFvemhvdSIsInNpZCI6IklxcG8tU2lCVzNYME1NV1NXNG5TR3pSNkM0NC5TVTFUTFVKbGJuUnNaWGt0VlZNLkg5MUwuclVQUHR3MTR1YU5idnBTaUh6UnBIbTZZTSIsIm5iZiI6MTYyOTQ3NzkyNywidWx0aW1hdGVfc2l0ZSI6IjEwMDEzODQyMzMiLCJ1c2FnZV9jb3VudHJ5X2lzbyI6IlVTIiwiYXV0aF90aW1lIjoxNjI5NDc4MjI3LCJuYW1lIjoiaGhlQGhhbGV5YWxkcmljaC5jb20iLCJvcmdfbmFtZSI6IkhhbGV5IGFuZCBBbGRyaWNoIEluYyIsImZhbWlseV9uYW1lIjoiSGUiLCJlbWFpbCI6ImhoZUBoYWxleWFsZHJpY2guY29tIiwiZXhwIjoxNjI5NDgxODI4fQ.ZMJO8zfzNJZVoWkjdKuIQOXvQmOkmBb_CbBNdlwrpJQGgTZvOHNMLCwOpFo5iDCwN3tDH5cCcBvOYofFLoJOxCvI3rKWKd4of_UN3sfSfDaaToVGhXIce4pR78hhAM29AqN5-fRMroGKBPwNp5CqDab5YTDp6rDcGTHpY_vgDMIfE1zwvNaezex81dbVn3F8kASmYZy_5DCTql_Nuiqn0qB3WS5FbfpqGcAMrz5CeUF9nnNeeusxUDNUKzSIhF2dgHBQvGETcFDtffgvAm0wbFL7tBK11wFGc7NT7wDw8RzJU4oRBJmE4B06bwyzItQQztheqXB2d5ahv9Nh-KFpOA"
      


# Get all the projectnames in the database, and select the project that user wants to investigate. 
# User needs to modify the value of `project` to select the project

# In[3]:


id_dict = sp.proj_name(token)

## Type the project name.
# Here the project we want to investigate is 0200157
project = '0200157'


# Now request data from the Openground database. 

# In[4]:


query_data = sp.query_data(id_dict, token, project)


# The requested data is in `json` format. Now convert it to `dataframe` to facilitate later calculaton.

# In[5]:


data_store = sp.archive_data(query_data)


# <div class="alert alert-success" role="alert">
#    Click "+" to review the datasheet.
# </div>

# In[6]:


# Review the data. 
import pandas as pd
pd.set_option('display.max_rows', None)
data_store


# ## SPT and Soil Properties Interpolation 

# User needs to type in the hammer type and borhole diameter for the N value correction. This should be stored in Openground database. But for now, due to the time limit, we have not found the path for these two values. This can be updated in the future. 

# In[7]:


# type boring parameters
hammer_type = 'safety_hammer'
borehole_diameter = 4  # unit: in


# Call function `spt_cal` to get soil properties. Here we take the calculation of friction angle as an example. Other properties can be calculated by updating `spt_cal` in `hapy`.
# 
# <div class="alert alert-success" role="alert">
#    Click "+" to review calculation results.
# </div>

# In[8]:


data_store = sp.spt_cal(data_store, hammer_type, borehole_diameter)
data_store


# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:




